#!/usr/bin/env bash

export APP_DIR=$HOME/sokratbot

while read oldrev newrev refname
do
    branch=$(echo $refname | cut -d/ -f3)
    if [ "master" == "$branch" ]; then
        export GIT_WORK_TREE=$APP_DIR

        cmd="git checkout -f"
        echo "Checkout repo"
        echo "  $cmd"
        $cmd
    else
        echo "Non-master branch was received. Do nothing."
    fi
done
